// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact-section" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSectionSection(): React.JSX.Element {
  return (
    <div id="contact-section" data-section="contact-section">
        <SectionErrorBoundary name="contact-section">
              <ContactCta
          tag="Kontakt os"
          text="Lad os diskutere din næste placering eller kampagne."
          primaryButton={{
            text: "Send besked",
            href: "#",
          }}
          secondaryButton={{
            text: "Ring nu",
            href: "tel:+4500000000",
          }}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
