// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonialParallax from '@/components/sections/about/AboutTestimonialParallax';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTestimonialParallax
          tag="Om os"
          quote="Vi bygger bro mellem byggepladser og brands."
          author="Urban OOH Team"
          role="Media Partner"
          videoSrc="https://storage.googleapis.com/webild/default/video-placeholder.mp4"
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
