// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboard from '@/components/sections/hero/HeroBillboard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboard
          title="Forvandl byggeplads til premium medieflade."
          description="Urban OOH forbinder brands med de stærkeste storformat-placeringer i Danmark."
          primaryButton={{
            text: "For bygherrer",        href: "/bygherrer"}}
          secondaryButton={{
            text: "For annoncører",        href: "/annoncoerer"}}
          imageSrc="https://storage.googleapis.com/webild/users/user_3FrMethFYMocawsrxMGgPOOqDSP/uploaded-1782900317840-e2y1mi42.jpg"
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
