// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Resultater"
          title="Synlighed der flytter noget."
          description="Vi skaber markant impact for brands i byrummet."
          metrics={[
            {
              value: "200k+",          title: "Månedlige visninger",          features: [
                "Høj trafik flow",            "Unik lokation",            "Primetid eksponering"],
            },
            {
              value: "98%",          title: "Kampagne recall",          features: [
                "Høj gennemslagskraft",            "Kreativ frihed",            "TOP  format"],
            },
            {
              value: "TOP ",          title: "lokationer",          features: [
                "Vækst i byer",            "Strategisk valg",            "Bygherre fokus"],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
