// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonial" section.

import React from 'react';
import TestimonialTrustCard from '@/components/sections/testimonial/TestimonialTrustCard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialSection(): React.JSX.Element {
  return (
    <div id="testimonial" data-section="testimonial">
        <SectionErrorBoundary name="testimonial">
              <TestimonialTrustCard
          quote="Urban OOH har transformeret vores byggeplads til en moderne medieflade. En professionel proces fra start til slut."
          rating={5}
          author="Jesper Vester, Vester Byg"
          avatars={[
            {
              name: "Anders",          imageSrc: "http://img.b2bpic.net/free-photo/male-cool-influencer-hosting-live-presentation-with-hands-free-microphone_482257-126542.jpg"},
            {
              name: "Mette",          imageSrc: "http://img.b2bpic.net/free-photo/young-stylish-woman-exploring-city_23-2149186681.jpg"},
            {
              name: "Søren",          imageSrc: "http://img.b2bpic.net/free-photo/young-japanese-woman-outdoors_23-2149010153.jpg"},
            {
              name: "Trine",          imageSrc: "http://img.b2bpic.net/free-photo/young-adult-traveling-london_23-2149259455.jpg"},
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
