/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { Star } from "lucide-react";
import { cls } from "@/lib/utils";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";

const testimonials = [
  {
    name: "Magnus Ebbesen",
    role: "Client Manager",
    company: "Dentsu",
    rating: 5
  },
  {
    name: "Christian Petersson",
    role: "Project Development Manager",
    company: "Urban Partners",
    rating: 5
  },
  {
    name: "Søren Haunstrup",
    role: "Administerende direktør",
    company: "S2 consult",
    rating: 5
  },
  {
    name: "Kasper Højmann",
    role: "Brand marketing manager",
    company: "HISENSE",
    rating: 5
  },
  {
    name: "Stephan Koldbjerg",
    role: "Media & Marketing manager",
    company: "LIDL",
    rating: 5
  }
];

type Testimonial = {
  name: string;
  role: string;
  company: string;
  rating: number;
  imageSrc?: string;
  videoSrc?: string;
};

const TestimonialsInline = () => {
  const duplicated = [...testimonials, ...testimonials, ...testimonials, ...testimonials];

  return (
    <section aria-label="Testimonials section" className="pt-20 pb-10">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Cases"}</p>
          </div>

          <TextAnimation
            text={"Vi skaber værdi for alle parter."}
            variant={"fade"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Hør hvad bygherrer og mediebureauer siger."}
            variant={"fade"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary" />}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <ScrollReveal variant="slide-up">
          <div className="w-content-width mx-auto overflow-hidden mask-fade-x-medium">
            <div className="flex w-max animate-marquee-horizontal" style={{ animationDuration: "60s" }}>
              {duplicated.map((testimonial, i) => (
                <div key={i} className="relative shrink-0 w-60 md:w-75 2xl:w-80 aspect-4/5 mb-10 mr-3 md:mr-5 rounded overflow-hidden card">
                  <div className="absolute inset-x-4 bottom-4 xl:inset-x-5 xl:bottom-5 2xl:inset-x-6 2xl:bottom-6 flex flex-col gap-1 xl:gap-2 2xl:gap-3 p-4 xl:p-5 2xl:p-6">
                    <div className="flex gap-1.5 mb-1">
                      {Array.from({ length: 5 }).map((_, index) => (
                        <Star
                          key={index}
                          className={cls(
                            "size-5 text-accent",
                            index < testimonial.rating ? "fill-accent" : "fill-transparent"
                          )}
                          strokeWidth={1.5}
                        />
                      ))}
                    </div>

                    <span className="text-2xl font-semibold leading-snug truncate">{testimonial.name}</span>

                    <div className="flex flex-col">
                      <span className="text-base leading-snug truncate">{testimonial.role}</span>
                      <span className="text-base leading-snug truncate">{testimonial.company}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function TestimonialsSection() {
  return (
    <div data-webild-section="testimonials" id="testimonials">
      <TestimonialsInline />
    </div>
  );
}
